name: Scheduled Tests

on:
  schedule:
   # This cron expression triggers at 6:00 AM UTC every day (2:00 AM EDT)
    - cron: '0 6 * * *'

jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest -v --disable-warnings
